name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64, chacha-runner]

    steps:
      - uses: actions/checkout@v4

      - name: Verify runner
        run: echo "✅ Self-hosted runner is working for ${{ github.repository }}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
